### ISSUE TITLE
Feature request: przewidywany czas ogłoszenia wyników

### ISSUE THREAD

**Issue by tpietruszka** [mini-pw/DataScienceInnovators#1]
Szanowni Państwo, 

Czy konkurs został odwołany?
Jeśli nie, czy jest jakaś przewidywana data ogłoszenia wyników?

Oczywiście zdaję sobie sprawę z faktu, że w obecnej sytuacji wiele planów trzeba było zmienić. Mimo tego, jakiś bardzo krótki update byłby bardzo przydatny - bo teraz strona konkursu wydaje się porzucona.

**Comment by pbiecek** [comment]
Dzień dobry,

Wyniki konkursu zostaną przestawione na gali online w dniu 4 czerwca.
Więcej informacji o tym wydarzeniu pojawi się już wkrótce na stronie www oraz zostanie przesłana mailowo.

Pandemia covid19 pomieszała nam szyki jeżeli chodzi o sposób zaprezentowania najlepszych prac.
Ale komisja konkursowa już oceniła ponad 60 zgłoszonych prac oraz wybrała laureatów.
